# # Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'
#
# target 'iosApp' do
#   # Comment the next line if you don't want to use dynamic frameworks
#   use_frameworks!
#
#   # Pods for iosApp
#   pod 'Firebase/Auth'
#   pod 'Firebase/Core'
#   pod 'Firebase/Analytics'
#
# end
#
target 'iosApp' do
  use_frameworks!
  platform :ios, '16.0'
  pod 'FirebaseAuth'
  pod 'GoogleSignIn'
#   pod 'composeApp', :path => '../composeApp'
end